# QIJI Agent 后端 Nginx 伪静态配置
# 复制到 宝塔 → 网站 → 设置 → 伪静态

location ~* (runtime|application)/ {
    deny all;
}

location / {
    if (!-e $request_filename) {
        rewrite  ^(.*)$  /index.php/$1  last;
        break;
    }
}
